### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'input_data/Green_Red_FarRed_Annotated_FISH_Dilation4Conn1Iter_Testing_128by128_normalize_dropout_Mask_ Pred_cshpaper.npy'

### ISSUE THREAD

**Issue by lunasdejavu** [CBIIT/Misteli-Lab-CCR-NCI#1]
hi there is an error showed up,
FileNotFoundError: [Errno 2] No such file or directory: 'input_data/Green_Red_FarRed_Annotated_FISH_Dilation4Conn1Iter_Testing_128by128_normalize_dropout_Mask_
Pred_cshpaper.npy'
it seems that you didn't put the file in the input_data folder.

**Comment by gudlap** [comment]
Hi -

The "predict" function in the Python file should be able to generate the "prediction" masks NUMPY file. The DNN weights (.h5) is in the repo. Would that help?

**Comment by lunasdejavu** [comment]
but it can't generate now
I think it might be the problem of version python and keras.
I can run train until that line under python 3.6.7 windows 7 keras 2.2.7 tensorflow 1.12.0,
but I can't train under python 3.6.8 ubuntu16.04  keras 2.2.7 tensorflow.1.12.0 .
I tried to use imshow () instead of  np.save()
     ```
from PIL import Image
     for i in range(imgs_mask_test.shape[0]):
          print(imgs_mask_test[i,:,:].shape)
          img = Image.fromarray(np.squeeze(imgs_mask_test[i,:,:]),'L')
           img.show()
```
but  I only see some weird binary images ,which the white spot doesn't look like the maskes HER2
then I tried to show imgs_test in this way.
there are  only binary images I can see like this:
<img width="393" alt="未命名3" src="https://user-images.githubusercontent.com/7753153/54581725-e0bb9000-4a48-11e9-855b-1ee0bfd2fd10.png">

> Hi -
> 
> The "predict" function in the Python file should be able to generate the "prediction" masks NUMPY file. The DNN weights (.h5) is in the repo. Would that help?

**Comment by gudlap** [comment]
Hi -

It might be an issue with Python+Keras+TF version. I've tested this on using python/anaconda versions on CentOS Linux release 7.5.1804 (Core) with Nvidia P100 GPUs (the GPU shouldn't matter).

Python==2.7.15 (anaconda custom 64-bit)
Keras==2.1.6
Tensorflow-GPU==1.12.0

Python==3.6.8 (anaconda custom 64-bit)
Keras==2.1.6
Tensorflow-GPU==1.12.0

I've also added a function ("plot_prediction") for displaying the prediction of FISH signal(s). Note that the input is a normalized [0, 1] float32 (numpy array) and the UNet is trying to predict the binary masks of FISH signals (dots). The output from the UNet will be a prob. of each pixel being foreground.

Here is a screenshot of matplotlib plot from  "plot_prediction":

![example_prediction](https://user-images.githubusercontent.com/22301332/54623597-3a6c8c00-4a42-11e9-8649-7f74cc26570f.png)

Hope this helps.

**Comment by lunasdejavu** [comment]
> a normalized [0, 1] float32 (numpy array

Thank you for your reply!
so I have to multiple 255 all the  images in npy format  to show them?
May I ask you the code of the plot_prediction?

**Comment by lunasdejavu** [comment]
I didn't found plot_prediction on GitHub... I am just wondering how to combine the mask of the result and the test images together?

**Comment by gudlap** [comment]
Hi -
It is here: [def plot_prediction():](https://github.com/CBIIT/Misteli-Lab-CCR-NCI/blob/8427522996fb0ea914c603b7619b694c649355ce/Gudla_CSH_2017/CNN_Python_Keras_TF/training/train_short_normalized_dropout_csh_paper_npy.py#L154)

Please feel free to reuse the logic for your own plotting.

**Comment by morty-top** [comment]
> hi there is an error showed up, FileNotFoundError: [Errno 2] No such file or directory: 'input_data/Green_Red_FarRed_Annotated_FISH_Dilation4Conn1Iter_Testing_128by128_normalize_dropout_Mask_ Pred_cshpaper.npy' it seems that you didn't put the file in the input_data folder.

hi,
Did you get the correct result? The npy file I run is not the same as the author's. And I did not find the reason.
